[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=[
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "era-contracts/contracts=lib/era-contracts/l1-contracts/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
